- name: Gather and print Ansible facts
  hosts: local
  connection: local
  gather_facts: yes  # Automatically runs ansible.builtin.setup

  tasks:
    - name: Print all facts
      ansible.builtin.debug:
        msg: ansible_facts
