- name: Play level variable
  hosts: local
  connection: local
  vars_files:
    - staticvars.yaml
  vars:
    COURSE: "This is from Play level variable"
  tasks:
    - name: variables print
      vars:
        COURSE: "This is from task variable"
      ansible.builtin.debug:
        msg: "{{ COURSE }}"