- name: Play level variable
  hosts: local
  connection: local
  vars:
    COURSE: "This the variable from the play"
  tasks:
    - name: printing the variables
      ansible.builting.debug:
        msg: "{{ COURSE}}"
