- name: Play level variable
  hosts: local
  connection: local
  vars:
    COURSE: "This is from Play level variable"
  tasks:
    - name: variables print
      ansible.builtin.debug:
        msg: "{{ COURSE }}"